site_name: PythonETL
nav:
  - Home: index.md
  - API: api.md

repo_name: "aloisiomartinez/python-excel-etl"
repo_url: "https://github.com/aloisiomartinez/python-excel-etl"

plugins:
  - search
  - mkdocstrings:
      default_handler: python
